name: Auto Pull on Main Commit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  auto_pull:
    runs-on: self-hosted

    steps:
      - name: Ping host by touching a temp file
        working-directory: /tmp
        run: |
          touch creative-staging-php70-github-workflow.tmp

      # - name: Check out code
      #   uses: actions/checkout@v2

      - name: Pull
        working-directory: ${{ vars.PROD_WORKDIR }}
        run: |
         pwd
         git pull
