name: Auto Pull on Main Commit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  auto_pull:
    runs-on: ubuntu-16.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Change directory
        run: |
          cd $DIRECTORY_PATH

      - name: Pull from server
        run: |
          git pull
