name: Auto Pull on Main Commit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  auto_pull:
    runs-on: self-hosted

    steps:
      - name: Ping host by touching a temp file
        run: |
          touch /tmp/creative-staging-php70-github-workflow.tmp
      
      # - name: Check out code
      #  uses: actions/checkout@v2

      # - name: Ping host by touching a temp file
      #  run: |
      #    touch /tmp/workflow.tmp

      - name: Change directory
        run: |
         cd $CREATIVESTAGINGPHP70WORKDIR

      - name: Display directory
        run: |
         pwd

      # - name: Pull from server
      #  run: |
      #    git pull
